$(document).ready(function(){
	//console.log("Hello");
	$('section').click(function(){
		$('.hexagon').fadeToggle('slow');
		$('.hexagon').promise().done(function(){
			$(this).fadeToggle(4600);
		});
		//$('.hexagon:nth-child(1)').toggle('slow'));
		console.log("argh");
	});
});